/* Copyright 2010-present MongoDB Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.IO;
using MongoDB.Bson.IO;
using MongoDB.Bson.Serialization;
using MongoDB.Bson.Serialization.Conventions;

namespace MongoDB.Bson.Builders;

/* All the interfaces here contain the methods from the respective domain/classes that can be used for lookups.
 * These are the interfaces generated by the builders and that we can pass around.
 */

internal interface IBsonSerializationDomain1
{
    bool IsTypeDiscriminated(Type type);

    Type LookupActualType(Type nominalType, BsonValue discriminator);

    IDiscriminatorConvention LookupDiscriminatorConvention(Type type);

    IIdGenerator LookupIdGenerator(Type type);

    IBsonSerializer<T> LookupSerializer<T>();

    IBsonSerializer LookupSerializer(Type type);

    IBsonSerializerRegistry SerializerRegistry { get; }

    TNominalType Deserialize<TNominalType>(BsonDocument document,
        Action<BsonDeserializationContext.Builder> configurator = null);

    TNominalType Deserialize<TNominalType>(IBsonReader bsonReader,
        Action<BsonDeserializationContext.Builder> configurator = null);

    TNominalType Deserialize<TNominalType>(byte[] bytes,
        Action<BsonDeserializationContext.Builder> configurator = null);

    TNominalType Deserialize<TNominalType>(Stream stream,
        Action<BsonDeserializationContext.Builder> configurator = null);

    TNominalType Deserialize<TNominalType>(string json,
        Action<BsonDeserializationContext.Builder> configurator = null);

    TNominalType Deserialize<TNominalType>(TextReader textReader,
        Action<BsonDeserializationContext.Builder> configurator = null);

    object Deserialize(BsonDocument document, Type nominalType,
        Action<BsonDeserializationContext.Builder> configurator = null);

    object Deserialize(IBsonReader bsonReader, Type nominalType,
        Action<BsonDeserializationContext.Builder> configurator = null);

    object Deserialize(byte[] bytes, Type nominalType,
        Action<BsonDeserializationContext.Builder> configurator = null);

    object Deserialize(Stream stream, Type nominalType,
        Action<BsonDeserializationContext.Builder> configurator = null);

    object Deserialize(string json, Type nominalType,
        Action<BsonDeserializationContext.Builder> configurator = null);

    object Deserialize(TextReader textReader, Type nominalType,
        Action<BsonDeserializationContext.Builder> configurator = null);

    void Serialize<TNominalType>(
        IBsonWriter bsonWriter,
        TNominalType value,
        Action<BsonSerializationContext.Builder> configurator = null,
        BsonSerializationArgs args = default(BsonSerializationArgs));

    void Serialize(
        IBsonWriter bsonWriter,
        Type nominalType,
        object value,
        Action<BsonSerializationContext.Builder> configurator = null,
        BsonSerializationArgs args = default(BsonSerializationArgs));

    IBsonClassMapDomain1 BsonClassMap { get; }

    IConventionRegistryDomain1 ConventionRegistry { get; }

    IBsonDefaults1 BsonDefaults { get; }
}

internal interface IBsonClassMapDomain1
{
    IEnumerable<BsonClassMap> GetRegisteredClassMaps();

    bool IsClassMapRegistered(Type type);

    BsonClassMap LookupClassMap(Type classType);
}

internal interface IConventionRegistryDomain1
{
    IConventionPack Lookup(Type type);
}

internal interface IBsonDefaults1
{
    IBsonSerializer DynamicArraySerializer { get; }
    IBsonSerializer DynamicDocumentSerializer { get; }
    int MaxDocumentSize { get; }
    int MaxSerializationDepth { get; }
}