/* Copyright 2010-present MongoDB Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace MongoDB.Driver.Linq3.Methods
{
    public static class EnumerableMethod
    {
        // private static fields
        private static readonly MethodInfo __aggregate;
        private static readonly MethodInfo __aggregateWithSeedAndFunc;
        private static readonly MethodInfo __aggregateWithSeedFuncAndResultSelector;
        private static readonly MethodInfo __all;
        private static readonly MethodInfo __any;
        private static readonly MethodInfo __anyWithPredicate;
        private static readonly MethodInfo __averageDecimal;
        private static readonly MethodInfo __averageDecimalWithSelector;
        private static readonly MethodInfo __averageDouble;
        private static readonly MethodInfo __averageDoubleWithSelector;
        private static readonly MethodInfo __averageInt32;
        private static readonly MethodInfo __averageInt32WithSelector;
        private static readonly MethodInfo __averageInt64;
        private static readonly MethodInfo __averageInt64WithSelector;
        private static readonly MethodInfo __averageNullableDecimal;
        private static readonly MethodInfo __averageNullableDecimalWithSelector;
        private static readonly MethodInfo __averageNullableDouble;
        private static readonly MethodInfo __averageNullableDoubleWithSelector;
        private static readonly MethodInfo __averageNullableInt32;
        private static readonly MethodInfo __averageNullableInt32WithSelector;
        private static readonly MethodInfo __averageNullableInt64;
        private static readonly MethodInfo __averageNullableInt64WithSelector;
        private static readonly MethodInfo __averageNullableSingle;
        private static readonly MethodInfo __averageNullableSingleWithSelector;
        private static readonly MethodInfo __averageSingle;
        private static readonly MethodInfo __averageSingleWithSelector;
        private static readonly MethodInfo __cast;
        private static readonly MethodInfo __concat;
        private static readonly MethodInfo __contains;
        private static readonly MethodInfo __count;
        private static readonly MethodInfo __countWithPredicate;
        private static readonly MethodInfo __defaultIfEmpty;
        private static readonly MethodInfo __defaultIfEmptyWithDefaultValue;
        private static readonly MethodInfo __distinct;
        private static readonly MethodInfo __elementAt;
        private static readonly MethodInfo __elementAtOrDefault;
        private static readonly MethodInfo __except;
        private static readonly MethodInfo __first;
        private static readonly MethodInfo __firstOrDefault;
        private static readonly MethodInfo __firstOrDefaultWithPredicate;
        private static readonly MethodInfo __firstWithPredicate;
        private static readonly MethodInfo __groupBy;
        private static readonly MethodInfo __groupByWithKeySelectorAndElementSelector;
        private static readonly MethodInfo __groupByWithKeySelectorAndResultSelector;
        private static readonly MethodInfo __groupByWithKeySelectorElementSelectorAndResultSelector;
        private static readonly MethodInfo __groupJoin;
        private static readonly MethodInfo __intersect;
        private static readonly MethodInfo __join;
        private static readonly MethodInfo __last;
        private static readonly MethodInfo __lastOrDefault;
        private static readonly MethodInfo __lastOrDefaultWithPredicate;
        private static readonly MethodInfo __lastWithPredicate;
        private static readonly MethodInfo __longCount;
        private static readonly MethodInfo __longCountWithPredicate;
        private static readonly MethodInfo __max;
        private static readonly MethodInfo __maxDecimal;
        private static readonly MethodInfo __maxDecimalWithSelector;
        private static readonly MethodInfo __maxDouble;
        private static readonly MethodInfo __maxDoubleWithSelector;
        private static readonly MethodInfo __maxInt32;
        private static readonly MethodInfo __maxInt32WithSelector;
        private static readonly MethodInfo __maxInt64;
        private static readonly MethodInfo __maxInt64WithSelector;
        private static readonly MethodInfo __maxNullableDecimal;
        private static readonly MethodInfo __maxNullableDecimalWithSelector;
        private static readonly MethodInfo __maxNullableDouble;
        private static readonly MethodInfo __maxNullableDoubleWithSelector;
        private static readonly MethodInfo __maxNullableInt32;
        private static readonly MethodInfo __maxNullableInt32WithSelector;
        private static readonly MethodInfo __maxNullableInt64;
        private static readonly MethodInfo __maxNullableInt64WithSelector;
        private static readonly MethodInfo __maxNullableSingle;
        private static readonly MethodInfo __maxNullableSingleWithSelector;
        private static readonly MethodInfo __maxSingle;
        private static readonly MethodInfo __maxSingleWithSelector;
        private static readonly MethodInfo __maxWithSelector;
        private static readonly MethodInfo __min;
        private static readonly MethodInfo __minDecimal;
        private static readonly MethodInfo __minDecimalWithSelector;
        private static readonly MethodInfo __minDouble;
        private static readonly MethodInfo __minDoubleWithSelector;
        private static readonly MethodInfo __minInt32;
        private static readonly MethodInfo __minInt32WithSelector;
        private static readonly MethodInfo __minInt64;
        private static readonly MethodInfo __minInt64WithSelector;
        private static readonly MethodInfo __minNullableDecimal;
        private static readonly MethodInfo __minNullableDecimalWithSelector;
        private static readonly MethodInfo __minNullableDouble;
        private static readonly MethodInfo __minNullableDoubleWithSelector;
        private static readonly MethodInfo __minNullableInt32;
        private static readonly MethodInfo __minNullableInt32WithSelector;
        private static readonly MethodInfo __minNullableInt64;
        private static readonly MethodInfo __minNullableInt64WithSelector;
        private static readonly MethodInfo __minNullableSingle;
        private static readonly MethodInfo __minNullableSingleWithSelector;
        private static readonly MethodInfo __minSingle;
        private static readonly MethodInfo __minSingleWithSelector;
        private static readonly MethodInfo __minWithSelector;
        private static readonly MethodInfo __ofType;
        private static readonly MethodInfo __orderBy;
        private static readonly MethodInfo __orderByDescending;
        private static readonly MethodInfo __range;
        private static readonly MethodInfo __repeat;
        private static readonly MethodInfo __reverse;
        private static readonly MethodInfo __select;
        private static readonly MethodInfo __selectMany;
        private static readonly MethodInfo __selectManyWithCollectionSelectorAndResultSelector;
        private static readonly MethodInfo __selectManyWithCollectionSelectorTakingIndexAndResultSelector;
        private static readonly MethodInfo __selectManyWithSelectorTakingIndex;
        private static readonly MethodInfo __selectWithSelectorTakingIndex;
        private static readonly MethodInfo __sequenceEqual;
        private static readonly MethodInfo __single;
        private static readonly MethodInfo __singleOrDefault;
        private static readonly MethodInfo __singleOrDefaultWithPredicate;
        private static readonly MethodInfo __singleWithPredicate;
        private static readonly MethodInfo __skip;
        private static readonly MethodInfo __sumDecimal;
        private static readonly MethodInfo __sumDecimalWithSelector;
        private static readonly MethodInfo __sumDouble;
        private static readonly MethodInfo __sumDoubleWithSelector;
        private static readonly MethodInfo __sumInt32;
        private static readonly MethodInfo __sumInt32WithSelector;
        private static readonly MethodInfo __sumInt64;
        private static readonly MethodInfo __sumInt64WithSelector;
        private static readonly MethodInfo __sumNullableDecimal;
        private static readonly MethodInfo __sumNullableDecimalWithSelector;
        private static readonly MethodInfo __sumNullableDouble;
        private static readonly MethodInfo __sumNullableDoubleWithSelector;
        private static readonly MethodInfo __sumNullableInt32;
        private static readonly MethodInfo __sumNullableInt32WithSelector;
        private static readonly MethodInfo __sumNullableInt64;
        private static readonly MethodInfo __sumNullableInt64WithSelector;
        private static readonly MethodInfo __sumNullableSingle;
        private static readonly MethodInfo __sumNullableSingleWithSelector;
        private static readonly MethodInfo __sumSingle;
        private static readonly MethodInfo __sumSingleWithSelector;
        private static readonly MethodInfo __take;
        private static readonly MethodInfo __thenBy;
        private static readonly MethodInfo __thenByDescending;
        private static readonly MethodInfo __toList;
        private static readonly MethodInfo __union;
        private static readonly MethodInfo __where;
        private static readonly MethodInfo __whereWithPredicateTakingIndex;
        private static readonly MethodInfo __zip;

        // static constructor
        static EnumerableMethod()
        {
            __aggregate = new Func<IEnumerable<object>, Func<object, object, object>, object>(Enumerable.Aggregate).Method.GetGenericMethodDefinition();
            __aggregateWithSeedAndFunc = new Func<IEnumerable<object>, object, Func<object, object, object>, object>(Enumerable.Aggregate).Method.GetGenericMethodDefinition();
            __aggregateWithSeedFuncAndResultSelector = new Func<IEnumerable<object>, object, Func<object, object, object>, Func<object, object>, object>(Enumerable.Aggregate).Method.GetGenericMethodDefinition();
            __all = new Func<IEnumerable<object>, Func<object, bool>, bool>(Enumerable.All).Method.GetGenericMethodDefinition();
            __any = new Func<IEnumerable<object>, bool>(Enumerable.Any).Method.GetGenericMethodDefinition();
            __anyWithPredicate = new Func<IEnumerable<object>, Func<object, bool>, bool>(Enumerable.Any).Method.GetGenericMethodDefinition();
            __averageDecimal = new Func<IEnumerable<decimal>, decimal>(Enumerable.Average).Method;
            __averageDecimalWithSelector = new Func<IEnumerable<object>, Func<object, decimal>, decimal>(Enumerable.Average).Method.GetGenericMethodDefinition();
            __averageDouble = new Func<IEnumerable<double>, double>(Enumerable.Average).Method;
            __averageDoubleWithSelector = new Func<IEnumerable<object>, Func<object, double>, double>(Enumerable.Average).Method.GetGenericMethodDefinition();
            __averageInt32 = new Func<IEnumerable<int>, double>(Enumerable.Average).Method;
            __averageInt32WithSelector = new Func<IEnumerable<object>, Func<object, int>, double>(Enumerable.Average).Method.GetGenericMethodDefinition();
            __averageInt64 = new Func<IEnumerable<long>, double>(Enumerable.Average).Method;
            __averageInt64WithSelector = new Func<IEnumerable<object>, Func<object, long>, double>(Enumerable.Average).Method.GetGenericMethodDefinition();
            __averageNullableDecimal = new Func<IEnumerable<decimal?>, decimal?>(Enumerable.Average).Method;
            __averageNullableDecimalWithSelector = new Func<IEnumerable<object>, Func<object, decimal?>, decimal?>(Enumerable.Average).Method.GetGenericMethodDefinition();
            __averageNullableDouble = new Func<IEnumerable<double?>, double?>(Enumerable.Average).Method;
            __averageNullableDoubleWithSelector = new Func<IEnumerable<object>, Func<object, double?>, double?>(Enumerable.Average).Method.GetGenericMethodDefinition();
            __averageNullableInt32 = new Func<IEnumerable<int?>, double?>(Enumerable.Average).Method;
            __averageNullableInt32WithSelector = new Func<IEnumerable<object>, Func<object, int?>, double?>(Enumerable.Average).Method.GetGenericMethodDefinition();
            __averageNullableInt64 = new Func<IEnumerable<long?>, double?>(Enumerable.Average).Method;
            __averageNullableInt64WithSelector = new Func<IEnumerable<object>, Func<object, long?>, double?>(Enumerable.Average).Method.GetGenericMethodDefinition();
            __averageNullableSingle = new Func<IEnumerable<float?>, float?>(Enumerable.Average).Method;
            __averageNullableSingleWithSelector = new Func<IEnumerable<object>, Func<object, float?>, float?>(Enumerable.Average).Method.GetGenericMethodDefinition();
            __averageSingle = new Func<IEnumerable<float>, float>(Enumerable.Average).Method;
            __averageSingleWithSelector = new Func<IEnumerable<object>, Func<object, float>, float>(Enumerable.Average).Method.GetGenericMethodDefinition();
            __cast = new Func<IEnumerable, IEnumerable<object>>(Enumerable.Cast<object>).Method.GetGenericMethodDefinition();
            __concat = new Func<IEnumerable<object>, IEnumerable<object>, IEnumerable<object>>(Enumerable.Concat).Method.GetGenericMethodDefinition();
            __contains = new Func<IEnumerable<object>, object, bool>(Enumerable.Contains).Method.GetGenericMethodDefinition();
            __count = new Func<IEnumerable<object>, int>(Enumerable.Count).Method.GetGenericMethodDefinition();
            __countWithPredicate = new Func<IEnumerable<object>, Func<object, bool>, int>(Enumerable.Count).Method.GetGenericMethodDefinition();
            __defaultIfEmpty = new Func<IEnumerable<object>, IEnumerable<object>>(Enumerable.DefaultIfEmpty).Method.GetGenericMethodDefinition();
            __defaultIfEmptyWithDefaultValue = new Func<IEnumerable<object>, object, IEnumerable<object>>(Enumerable.DefaultIfEmpty).Method.GetGenericMethodDefinition();
            __distinct = new Func<IEnumerable<object>, IEnumerable<object>>(Enumerable.Distinct).Method.GetGenericMethodDefinition();
            __elementAt = new Func<IEnumerable<object>, int, object>(Enumerable.ElementAt).Method.GetGenericMethodDefinition();
            __elementAtOrDefault = new Func<IEnumerable<object>, int, object>(Enumerable.ElementAt).Method.GetGenericMethodDefinition();
            __except = new Func<IEnumerable<object>, IEnumerable<object>, IEnumerable<object>>(Enumerable.Except).Method.GetGenericMethodDefinition();
            __first = new Func<IEnumerable<object>, object>(Enumerable.First).Method.GetGenericMethodDefinition();
            __firstOrDefault = new Func<IEnumerable<object>, object>(Enumerable.FirstOrDefault).Method.GetGenericMethodDefinition();
            __firstOrDefaultWithPredicate = new Func<IEnumerable<object>, Func<object, bool>, object>(Enumerable.FirstOrDefault).Method.GetGenericMethodDefinition();
            __firstWithPredicate = new Func<IEnumerable<object>, Func<object, bool>, object>(Enumerable.First).Method.GetGenericMethodDefinition();
            __groupBy = new Func<IEnumerable<object>, Func<object, object>, IEnumerable<IGrouping<object, object>>>(Enumerable.GroupBy).Method.GetGenericMethodDefinition();
            __groupByWithKeySelectorAndElementSelector = new Func<IEnumerable<object>, Func<object, object>, Func<object, object>, IEnumerable<IGrouping<object, object>>>(Enumerable.GroupBy).Method.GetGenericMethodDefinition();
            __groupByWithKeySelectorAndResultSelector = new Func<IEnumerable<object>, Func<object, object>, Func<object, object, object>, IEnumerable<object>>(Enumerable.GroupBy).Method.GetGenericMethodDefinition();
            __groupByWithKeySelectorElementSelectorAndResultSelector = new Func<IEnumerable<object>, Func<object, object>, Func<object, object>, Func<object, IEnumerable<object>, object>, IEnumerable<object>>(Enumerable.GroupBy).Method.GetGenericMethodDefinition();
            __groupJoin = new Func<IEnumerable<object>, IEnumerable<object>, Func<object, object>, Func<object, object>, Func<object, IEnumerable<object>, object>, IEnumerable<object>>(Enumerable.GroupJoin).Method.GetGenericMethodDefinition();
            __intersect = new Func<IEnumerable<object>, IEnumerable<object>, IEnumerable<object>>(Enumerable.Intersect).Method.GetGenericMethodDefinition();
            __join = new Func<IEnumerable<object>, IEnumerable<object>, Func<object, object>, Func<object, object>, Func<object, object, object>, IEnumerable<object>>(Enumerable.Join).Method.GetGenericMethodDefinition();
            __last = new Func<IEnumerable<object>, object>(Enumerable.Last).Method.GetGenericMethodDefinition();
            __lastOrDefault = new Func<IEnumerable<object>, object>(Enumerable.LastOrDefault).Method.GetGenericMethodDefinition();
            __lastOrDefaultWithPredicate = new Func<IEnumerable<object>, Func<object, bool>, object>(Enumerable.LastOrDefault).Method.GetGenericMethodDefinition();
            __lastWithPredicate = new Func<IEnumerable<object>, Func<object, bool>, object>(Enumerable.Last).Method.GetGenericMethodDefinition();
            __longCount = new Func<IEnumerable<object>, long>(Enumerable.LongCount).Method.GetGenericMethodDefinition();
            __longCountWithPredicate = new Func<IEnumerable<object>, Func<object, bool>, long>(Enumerable.LongCount).Method.GetGenericMethodDefinition();
            __max = new Func<IEnumerable<object>, object>(Enumerable.Max).Method.GetGenericMethodDefinition();
            __maxDecimal = new Func<IEnumerable<decimal>, decimal>(Enumerable.Max).Method;
            __maxDecimalWithSelector = new Func<IEnumerable<object>, Func<object, decimal>, decimal>(Enumerable.Max).Method.GetGenericMethodDefinition();
            __maxDouble = new Func<IEnumerable<double>, double>(Enumerable.Max).Method;
            __maxDoubleWithSelector = new Func<IEnumerable<object>, Func<object, double>, double>(Enumerable.Max).Method.GetGenericMethodDefinition();
            __maxInt32 = new Func<IEnumerable<int>, int>(Enumerable.Max).Method;
            __maxInt32WithSelector = new Func<IEnumerable<object>, Func<object, int>, int>(Enumerable.Max).Method.GetGenericMethodDefinition();
            __maxInt64 = new Func<IEnumerable<long>, long>(Enumerable.Max).Method;
            __maxInt64WithSelector = new Func<IEnumerable<object>, Func<object, long>, long>(Enumerable.Max).Method.GetGenericMethodDefinition();
            __maxNullableDecimal = new Func<IEnumerable<decimal?>, decimal?>(Enumerable.Max).Method;
            __maxNullableDecimalWithSelector = new Func<IEnumerable<object>, Func<object, decimal?>, decimal?>(Enumerable.Max).Method.GetGenericMethodDefinition();
            __maxNullableDouble = new Func<IEnumerable<double?>, double?>(Enumerable.Max).Method;
            __maxNullableDoubleWithSelector = new Func<IEnumerable<object>, Func<object, double?>, double?>(Enumerable.Max).Method.GetGenericMethodDefinition();
            __maxNullableInt32 = new Func<IEnumerable<int?>, int?>(Enumerable.Max).Method;
            __maxNullableInt32WithSelector = new Func<IEnumerable<object>, Func<object, int?>, int?>(Enumerable.Max).Method.GetGenericMethodDefinition();
            __maxNullableInt64 = new Func<IEnumerable<long?>, long?>(Enumerable.Max).Method;
            __maxNullableInt64WithSelector = new Func<IEnumerable<object>, Func<object, long?>, long?>(Enumerable.Max).Method.GetGenericMethodDefinition();
            __maxNullableSingle = new Func<IEnumerable<float?>, float?>(Enumerable.Max).Method;
            __maxNullableSingleWithSelector = new Func<IEnumerable<object>, Func<object, float?>, float?>(Enumerable.Max).Method.GetGenericMethodDefinition();
            __maxSingle = new Func<IEnumerable<float>, float>(Enumerable.Max).Method;
            __maxSingleWithSelector = new Func<IEnumerable<object>, Func<object, float>, float>(Enumerable.Max).Method.GetGenericMethodDefinition();
            __maxWithSelector = new Func<IEnumerable<object>, Func<object, object>, object>(Enumerable.Max).Method.GetGenericMethodDefinition();
            __min = new Func<IEnumerable<object>, object>(Enumerable.Min).Method.GetGenericMethodDefinition();
            __minDecimal = new Func<IEnumerable<decimal>, decimal>(Enumerable.Min).Method;
            __minDecimalWithSelector = new Func<IEnumerable<object>, Func<object, decimal>, decimal>(Enumerable.Min).Method.GetGenericMethodDefinition();
            __minDouble = new Func<IEnumerable<double>, double>(Enumerable.Min).Method;
            __minDoubleWithSelector = new Func<IEnumerable<object>, Func<object, double>, double>(Enumerable.Min).Method.GetGenericMethodDefinition();
            __minInt32 = new Func<IEnumerable<int>, int>(Enumerable.Min).Method;
            __minInt32WithSelector = new Func<IEnumerable<object>, Func<object, int>, int>(Enumerable.Min).Method.GetGenericMethodDefinition();
            __minInt64 = new Func<IEnumerable<long>, long>(Enumerable.Min).Method;
            __minInt64WithSelector = new Func<IEnumerable<object>, Func<object, long>, long>(Enumerable.Min).Method.GetGenericMethodDefinition();
            __minNullableDecimal = new Func<IEnumerable<decimal?>, decimal?>(Enumerable.Min).Method;
            __minNullableDecimalWithSelector = new Func<IEnumerable<object>, Func<object, decimal?>, decimal?>(Enumerable.Min).Method.GetGenericMethodDefinition();
            __minNullableDouble = new Func<IEnumerable<double?>, double?>(Enumerable.Min).Method;
            __minNullableDoubleWithSelector = new Func<IEnumerable<object>, Func<object, double?>, double?>(Enumerable.Min).Method.GetGenericMethodDefinition();
            __minNullableInt32 = new Func<IEnumerable<int?>, int?>(Enumerable.Min).Method;
            __minNullableInt32WithSelector = new Func<IEnumerable<object>, Func<object, int?>, int?>(Enumerable.Min).Method.GetGenericMethodDefinition();
            __minNullableInt64 = new Func<IEnumerable<long?>, long?>(Enumerable.Min).Method;
            __minNullableInt64WithSelector = new Func<IEnumerable<object>, Func<object, long?>, long?>(Enumerable.Min).Method.GetGenericMethodDefinition();
            __minNullableSingle = new Func<IEnumerable<float?>, float?>(Enumerable.Min).Method;
            __minNullableSingleWithSelector = new Func<IEnumerable<object>, Func<object, float?>, float?>(Enumerable.Min).Method.GetGenericMethodDefinition();
            __minSingle = new Func<IEnumerable<float>, float>(Enumerable.Min).Method;
            __minSingleWithSelector = new Func<IEnumerable<object>, Func<object, float>, float>(Enumerable.Min).Method.GetGenericMethodDefinition();
            __minWithSelector = new Func<IEnumerable<object>, Func<object, object>, object>(Enumerable.Min).Method.GetGenericMethodDefinition();
            __ofType = new Func<IEnumerable, IEnumerable<object>>(Enumerable.OfType<object>).Method.GetGenericMethodDefinition();
            __orderBy = new Func<IEnumerable<object>, Func<object, object>, IOrderedEnumerable<object>>(Enumerable.OrderBy).Method.GetGenericMethodDefinition();
            __orderByDescending = new Func<IEnumerable<object>, Func<object, object>, IOrderedEnumerable<object>>(Enumerable.OrderByDescending).Method.GetGenericMethodDefinition();
            __range = new Func<int, int, IEnumerable<int>>(Enumerable.Range).Method;
            __repeat = new Func<object, int, IEnumerable<object>>(Enumerable.Repeat).Method.GetGenericMethodDefinition();
            __reverse = new Func<IEnumerable<object>, IEnumerable<object>>(Enumerable.Reverse).Method.GetGenericMethodDefinition();
            __select = new Func<IEnumerable<object>, Func<object, object>, IEnumerable<object>>(Enumerable.Select).Method.GetGenericMethodDefinition();
            __selectMany = new Func<IEnumerable<object>, Func<object, IEnumerable<object>>, IEnumerable<object>>(Enumerable.SelectMany).Method.GetGenericMethodDefinition();
            __selectManyWithCollectionSelectorAndResultSelector = new Func<IEnumerable<object>, Func<object, IEnumerable<object>>, Func<object, object, object>, IEnumerable<object>>(Enumerable.SelectMany).Method.GetGenericMethodDefinition();
            __selectManyWithCollectionSelectorTakingIndexAndResultSelector = new Func<IEnumerable<object>, Func<object, int, IEnumerable<object>>, Func<object, object, object>, IEnumerable<object>>(Enumerable.SelectMany).Method.GetGenericMethodDefinition();
            __selectManyWithSelectorTakingIndex = new Func<IEnumerable<object>, Func<object, int, IEnumerable<object>>, IEnumerable<object>>(Enumerable.SelectMany).Method.GetGenericMethodDefinition();
            __selectWithSelectorTakingIndex = new Func<IEnumerable<object>, Func<object, int, object>, object>(Enumerable.Select).Method.GetGenericMethodDefinition();
            __sequenceEqual = new Func<IEnumerable<object>, IEnumerable<object>, bool>(Enumerable.SequenceEqual).Method.GetGenericMethodDefinition();
            __single = new Func<IEnumerable<object>, object>(Enumerable.Single).Method.GetGenericMethodDefinition();
            __singleOrDefault = new Func<IEnumerable<object>, object>(Enumerable.SingleOrDefault).Method.GetGenericMethodDefinition();
            __singleOrDefaultWithPredicate = new Func<IEnumerable<object>, Func<object, bool>, object>(Enumerable.SingleOrDefault).Method.GetGenericMethodDefinition();
            __singleWithPredicate = new Func<IEnumerable<object>, Func<object, bool>, object>(Enumerable.Single).Method.GetGenericMethodDefinition();
            __skip = new Func<IEnumerable<object>, int, IEnumerable<object>>(Enumerable.Skip).Method.GetGenericMethodDefinition();
            __sumDecimal = new Func<IEnumerable<decimal>, decimal>(Enumerable.Sum).Method;
            __sumDecimalWithSelector = new Func<IEnumerable<object>, Func<object, decimal>, decimal>(Enumerable.Sum).Method.GetGenericMethodDefinition();
            __sumDouble = new Func<IEnumerable<double>, double>(Enumerable.Sum).Method;
            __sumDoubleWithSelector = new Func<IEnumerable<object>, Func<object, double>, double>(Enumerable.Sum).Method.GetGenericMethodDefinition();
            __sumInt32 = new Func<IEnumerable<int>, int>(Enumerable.Sum).Method;
            __sumInt32WithSelector = new Func<IEnumerable<object>, Func<object, int>, int>(Enumerable.Sum).Method.GetGenericMethodDefinition();
            __sumInt64 = new Func<IEnumerable<long>, long>(Enumerable.Sum).Method;
            __sumInt64WithSelector = new Func<IEnumerable<object>, Func<object, long>, long>(Enumerable.Sum).Method.GetGenericMethodDefinition();
            __sumNullableDecimal = new Func<IEnumerable<decimal?>, decimal?>(Enumerable.Sum).Method;
            __sumNullableDecimalWithSelector = new Func<IEnumerable<object>, Func<object, decimal?>, decimal?>(Enumerable.Sum).Method.GetGenericMethodDefinition();
            __sumNullableDouble = new Func<IEnumerable<double?>, double?>(Enumerable.Sum).Method;
            __sumNullableDoubleWithSelector = new Func<IEnumerable<object>, Func<object, double?>, double?>(Enumerable.Sum).Method.GetGenericMethodDefinition();
            __sumNullableInt32 = new Func<IEnumerable<int?>, int?>(Enumerable.Sum).Method;
            __sumNullableInt32WithSelector = new Func<IEnumerable<object>, Func<object, int?>, int?>(Enumerable.Sum).Method.GetGenericMethodDefinition();
            __sumNullableInt64 = new Func<IEnumerable<long?>, long?>(Enumerable.Sum).Method;
            __sumNullableInt64WithSelector = new Func<IEnumerable<object>, Func<object, long?>, long?>(Enumerable.Sum).Method.GetGenericMethodDefinition();
            __sumNullableSingle = new Func<IEnumerable<float?>, float?>(Enumerable.Sum).Method;
            __sumNullableSingleWithSelector = new Func<IEnumerable<object>, Func<object, float?>, float?>(Enumerable.Sum).Method.GetGenericMethodDefinition();
            __sumSingle = new Func<IEnumerable<float>, float>(Enumerable.Sum).Method;
            __sumSingleWithSelector = new Func<IEnumerable<object>, Func<object, float>, float>(Enumerable.Sum).Method.GetGenericMethodDefinition();
            __take = new Func<IEnumerable<object>, int, IEnumerable<object>>(Enumerable.Take).Method.GetGenericMethodDefinition();
            __thenBy = new Func<IOrderedEnumerable<object>, Func<object, object>, IOrderedEnumerable<object>>(Enumerable.ThenBy).Method.GetGenericMethodDefinition();
            __thenByDescending = new Func<IOrderedEnumerable<object>, Func<object, object>, IOrderedEnumerable<object>>(Enumerable.ThenByDescending).Method.GetGenericMethodDefinition();
            __toList = new Func<IEnumerable<object>, List<object>>(Enumerable.ToList).Method.GetGenericMethodDefinition();
            __union = new Func<IEnumerable<object>, IEnumerable<object>, IEnumerable<object>>(Enumerable.Union).Method.GetGenericMethodDefinition();
            __where = new Func<IEnumerable<object>, Func<object, bool>, IEnumerable<object>>(Enumerable.Where).Method.GetGenericMethodDefinition();
            __whereWithPredicateTakingIndex = new Func<IEnumerable<object>, Func<object, int, bool>, IEnumerable<object>>(Enumerable.Where).Method.GetGenericMethodDefinition();
            __zip = new Func<IEnumerable<object>, IEnumerable<object>, Func<object, object, object>, IEnumerable<object>>(Enumerable.Zip).Method.GetGenericMethodDefinition();
        }

        // public properties
        public static MethodInfo Aggregate => __aggregate;
        public static MethodInfo AggregateWithSeedAndFunc => __aggregateWithSeedAndFunc;
        public static MethodInfo AggregateWithSeedFuncAndResultSelector => __aggregateWithSeedFuncAndResultSelector;
        public static MethodInfo All => __all;
        public static MethodInfo Any => __any;
        public static MethodInfo AnyWithPredicate => __anyWithPredicate;
        public static MethodInfo AverageDecimal => __averageDecimal;
        public static MethodInfo AverageDecimalWithSelector => __averageDecimalWithSelector;
        public static MethodInfo AverageDouble => __averageDouble;
        public static MethodInfo AverageDoubleWithSelector => __averageDoubleWithSelector;
        public static MethodInfo AverageInt32 => __averageInt32;
        public static MethodInfo AverageInt32WithSelector => __averageInt32WithSelector;
        public static MethodInfo AverageInt64 => __averageInt64;
        public static MethodInfo AverageInt64WithSelector => __averageInt64WithSelector;
        public static MethodInfo AverageNullableDecimal => __averageNullableDecimal;
        public static MethodInfo AverageNullableDecimalWithSelector => __averageNullableDecimalWithSelector;
        public static MethodInfo AverageNullableDouble => __averageNullableDouble;
        public static MethodInfo AverageNullableDoubleWithSelector => __averageNullableDoubleWithSelector;
        public static MethodInfo AverageNullableInt32 => __averageNullableInt32;
        public static MethodInfo AverageNullableInt32WithSelector => __averageNullableInt32WithSelector;
        public static MethodInfo AverageNullableInt64 => __averageNullableInt64;
        public static MethodInfo AverageNullableInt64WithSelector => __averageNullableInt64WithSelector;
        public static MethodInfo AverageNullableSingle => __averageNullableSingle;
        public static MethodInfo AverageNullableSingleWithSelector => __averageNullableSingleWithSelector;
        public static MethodInfo AverageSingle => __averageSingle;
        public static MethodInfo AverageSingleWithSelector => __averageSingleWithSelector;
        public static MethodInfo Cast => __cast;
        public static MethodInfo Concat => __concat;
        public static MethodInfo Contains => __contains;
        public static MethodInfo Count => __count;
        public static MethodInfo CountWithPredicate => __countWithPredicate;
        public static MethodInfo DefaultIfEmpty => __defaultIfEmpty;
        public static MethodInfo DefaultIfEmptyWithDefaultValue => __defaultIfEmptyWithDefaultValue;
        public static MethodInfo Distinct => __distinct;
        public static MethodInfo ElementAt => __elementAt;
        public static MethodInfo ElementAtOrDefault => __elementAtOrDefault;
        public static MethodInfo Except => __except;
        public static MethodInfo First => __first;
        public static MethodInfo FirstOrDefault => __firstOrDefault;
        public static MethodInfo FirstOrDefaultWithPredicate => __firstOrDefaultWithPredicate;
        public static MethodInfo FirstWithPredicate => __firstWithPredicate;
        public static MethodInfo GroupBy => __groupBy;
        public static MethodInfo GroupByWithKeySelectorAndElementSelector => __groupByWithKeySelectorAndElementSelector;
        public static MethodInfo GroupByWithKeySelectorAndResultSelector => __groupByWithKeySelectorAndResultSelector;
        public static MethodInfo GroupByWithKeySelectorElementSelectorAndResultSelector => __groupByWithKeySelectorElementSelectorAndResultSelector;
        public static MethodInfo GroupJoin => __groupJoin;
        public static MethodInfo Intersect => __intersect;
        public static MethodInfo Join => __join;
        public static MethodInfo Last => __last;
        public static MethodInfo LastOrDefault => __lastOrDefault;
        public static MethodInfo LastOrDefaultWithPredicate => __lastOrDefaultWithPredicate;
        public static MethodInfo LastWithPredicate => __lastWithPredicate;
        public static MethodInfo LongCount => __longCount;
        public static MethodInfo LongCountWithPredicate => __longCountWithPredicate;
        public static MethodInfo Max => __max;
        public static MethodInfo MaxDecimal => __maxDecimal;
        public static MethodInfo MaxDecimalWithSelector => __maxDecimalWithSelector;
        public static MethodInfo MaxDouble => __maxDouble;
        public static MethodInfo MaxDoubleWithSelector => __maxDoubleWithSelector;
        public static MethodInfo MaxInt32 => __maxInt32;
        public static MethodInfo MaxInt32WithSelector => __maxInt32WithSelector;
        public static MethodInfo MaxInt64 => __maxInt64;
        public static MethodInfo MaxInt64WithSelector => __maxInt64WithSelector;
        public static MethodInfo MaxNullableDecimal => __maxNullableDecimal;
        public static MethodInfo MaxNullableDecimalWithSelector => __maxNullableDecimalWithSelector;
        public static MethodInfo MaxNullableDouble => __maxNullableDouble;
        public static MethodInfo MaxNullableDoubleWithSelector => __maxNullableDoubleWithSelector;
        public static MethodInfo MaxNullableInt32 => __maxNullableInt32;
        public static MethodInfo MaxNullableInt32WithSelector => __maxNullableInt32WithSelector;
        public static MethodInfo MaxNullableInt64 => __maxNullableInt64;
        public static MethodInfo MaxNullableInt64WithSelector => __maxNullableInt64WithSelector;
        public static MethodInfo MaxNullableSingle => __maxNullableSingle;
        public static MethodInfo MaxNullableSingleWithSelector => __maxNullableSingleWithSelector;
        public static MethodInfo MaxSingle => __maxSingle;
        public static MethodInfo MaxSingleWithSelector => __maxSingleWithSelector;
        public static MethodInfo MaxWithSelector => __maxWithSelector;
        public static MethodInfo Min => __min;
        public static MethodInfo MinDecimal => __minDecimal;
        public static MethodInfo MinDecimalWithSelector => __minDecimalWithSelector;
        public static MethodInfo MinDouble => __minDouble;
        public static MethodInfo MinDoubleWithSelector => __minDoubleWithSelector;
        public static MethodInfo MinInt32 => __minInt32;
        public static MethodInfo MinInt32WithSelector => __minInt32WithSelector;
        public static MethodInfo MinInt64 => __minInt64;
        public static MethodInfo MinInt64WithSelector => __minInt64WithSelector;
        public static MethodInfo MinNullableDecimal => __minNullableDecimal;
        public static MethodInfo MinNullableDecimalWithSelector => __minNullableDecimalWithSelector;
        public static MethodInfo MinNullableDouble => __minNullableDouble;
        public static MethodInfo MinNullableDoubleWithSelector => __minNullableDoubleWithSelector;
        public static MethodInfo MinNullableInt32 => __minNullableInt32;
        public static MethodInfo MinNullableInt32WithSelector => __minNullableInt32WithSelector;
        public static MethodInfo MinNullableInt64 => __minNullableInt64;
        public static MethodInfo MinNullableInt64WithSelector => __minNullableInt64WithSelector;
        public static MethodInfo MinNullableSingle => __minNullableSingle;
        public static MethodInfo MinNullableSingleWithSelector => __minNullableSingleWithSelector;
        public static MethodInfo MinSingle => __minSingle;
        public static MethodInfo MinSingleWithSelector => __minSingleWithSelector;
        public static MethodInfo MinWithSelector => __minWithSelector;
        public static MethodInfo OfType => __ofType;
        public static MethodInfo OrderBy => __orderBy;
        public static MethodInfo OrderByDescending => __orderByDescending;
        public static MethodInfo Range => __range;
        public static MethodInfo Repeat => __repeat;
        public static MethodInfo Reverse => __reverse;
        public static MethodInfo Select => __select;
        public static MethodInfo SelectMany => __selectMany;
        public static MethodInfo SelectManyWithCollectionSelectorAndResultSelector => __selectManyWithCollectionSelectorAndResultSelector;
        public static MethodInfo SelectManyWithCollectionSelectorTakingIndexAndResultSelector => __selectManyWithCollectionSelectorTakingIndexAndResultSelector;
        public static MethodInfo SelectManyWithSelectorTakingIndex => __selectManyWithSelectorTakingIndex;
        public static MethodInfo SelectWithSelectorTakingIndex => __selectWithSelectorTakingIndex;
        public static MethodInfo SequenceEqual => __sequenceEqual;
        public static MethodInfo Single => __single;
        public static MethodInfo SingleOrDefault => __singleOrDefault;
        public static MethodInfo SingleOrDefaultWithPredicate => __singleOrDefaultWithPredicate;
        public static MethodInfo SingleWithPredicate => __singleWithPredicate;
        public static MethodInfo Skip => __skip;
        public static MethodInfo SumDecimal => __sumDecimal;
        public static MethodInfo SumDecimalWithSelector => __sumDecimalWithSelector;
        public static MethodInfo SumDouble => __sumDouble;
        public static MethodInfo SumDoubleWithSelector => __sumDoubleWithSelector;
        public static MethodInfo SumInt32 => __sumInt32;
        public static MethodInfo SumInt32WithSelector => __sumInt32WithSelector;
        public static MethodInfo SumInt64 => __sumInt64;
        public static MethodInfo SumInt64WithSelector => __sumInt64WithSelector;
        public static MethodInfo SumNullableDecimal => __sumNullableDecimal;
        public static MethodInfo SumNullableDecimalWithSelector => __sumNullableDecimalWithSelector;
        public static MethodInfo SumNullableDouble => __sumNullableDouble;
        public static MethodInfo SumNullableDoubleWithSelector => __sumNullableDoubleWithSelector;
        public static MethodInfo SumNullableInt32 => __sumNullableInt32;
        public static MethodInfo SumNullableInt32WithSelector => __sumNullableInt32WithSelector;
        public static MethodInfo SumNullableInt64 => __sumNullableInt64;
        public static MethodInfo SumNullableInt64WithSelector => __sumNullableInt64WithSelector;
        public static MethodInfo SumNullableSingle => __sumNullableSingle;
        public static MethodInfo SumNullableSingleWithSelector => __sumNullableSingleWithSelector;
        public static MethodInfo SumSingle => __sumSingle;
        public static MethodInfo SumSingleWithSelector => __sumSingleWithSelector;
        public static MethodInfo Take => __take;
        public static MethodInfo ThenBy => __thenBy;
        public static MethodInfo ThenByDescending => __thenByDescending;
        public static MethodInfo ToList => __toList;
        public static MethodInfo Union => __union;
        public static MethodInfo Where => __where;
        public static MethodInfo WhereWithPredicateTakingIndex => __whereWithPredicateTakingIndex;
        public static MethodInfo Zip => __zip;

        // public methods
        public static MethodInfo MakeSelect(Type sourceType, Type resultType)
        {
            return __select.MakeGenericMethod(sourceType, resultType);
        }

        public static MethodInfo MakeWhere(Type tsource)
        {
            return __where.MakeGenericMethod(tsource);
        }
    }
}
