/* Copyright 2010-present MongoDB Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace MongoDB.Driver.Linq3.Methods
{
    public static class MongoQueryableMethod
    {
        // private static fields
        private static readonly MethodInfo __anyAsync;
        private static readonly MethodInfo __anyWithPredicateAsync;
        private static readonly MethodInfo __averageDecimalAsync;
        private static readonly MethodInfo __averageDecimalWithSelectorAsync;
        private static readonly MethodInfo __averageDoubleAsync;
        private static readonly MethodInfo __averageDoubleWithSelectorAsync;
        private static readonly MethodInfo __averageInt32Async;
        private static readonly MethodInfo __averageInt32WithSelectorAsync;
        private static readonly MethodInfo __averageInt64Async;
        private static readonly MethodInfo __averageInt64WithSelectorAsync;
        private static readonly MethodInfo __averageNullableDecimalAsync;
        private static readonly MethodInfo __averageNullableDecimalWithSelectorAsync;
        private static readonly MethodInfo __averageNullableDoubleAsync;
        private static readonly MethodInfo __averageNullableDoubleWithSelectorAsync;
        private static readonly MethodInfo __averageNullableInt32Async;
        private static readonly MethodInfo __averageNullableInt32WithSelectorAsync;
        private static readonly MethodInfo __averageNullableInt64Async;
        private static readonly MethodInfo __averageNullableInt64WithSelectorAsync;
        private static readonly MethodInfo __averageNullableSingleAsync;
        private static readonly MethodInfo __averageNullableSingleWithSelectorAsync;
        private static readonly MethodInfo __averageSingleAsync;
        private static readonly MethodInfo __averageSingleWithSelectorAsync;
        private static readonly MethodInfo __countAsync;
        private static readonly MethodInfo __countWithPredicateAsync;
        private static readonly MethodInfo __firstAsync;
        private static readonly MethodInfo __firstOrDefaultAsync;
        private static readonly MethodInfo __firstOrDefaultWithPredicateAsync;
        private static readonly MethodInfo __firstWithPredicateAsync;
        private static readonly MethodInfo __longCountAsync;
        private static readonly MethodInfo __longCountWithPredicateAsync;
        private static readonly MethodInfo __maxAsync;
        private static readonly MethodInfo __maxWithSelectorAsync;
        private static readonly MethodInfo __minAsync;
        private static readonly MethodInfo __minWithSelectorAsync;
        private static readonly MethodInfo __sample;
        private static readonly MethodInfo __singleAsync;
        private static readonly MethodInfo __singleOrDefaultAsync;
        private static readonly MethodInfo __singleOrDefaultWithPredicateAsync;
        private static readonly MethodInfo __singleWithPredicateAsync;
        private static readonly MethodInfo __standardDeviationPopulationDecimal;
        private static readonly MethodInfo __standardDeviationPopulationDecimalAsync;
        private static readonly MethodInfo __standardDeviationPopulationDecimalWithSelector;
        private static readonly MethodInfo __standardDeviationPopulationDecimalWithSelectorAsync;
        private static readonly MethodInfo __standardDeviationPopulationDouble;
        private static readonly MethodInfo __standardDeviationPopulationDoubleAsync;
        private static readonly MethodInfo __standardDeviationPopulationDoubleWithSelector;
        private static readonly MethodInfo __standardDeviationPopulationDoubleWithSelectorAsync;
        private static readonly MethodInfo __standardDeviationPopulationInt32;
        private static readonly MethodInfo __standardDeviationPopulationInt32Async;
        private static readonly MethodInfo __standardDeviationPopulationInt32WithSelector;
        private static readonly MethodInfo __standardDeviationPopulationInt32WithSelectorAsync;
        private static readonly MethodInfo __standardDeviationPopulationInt64;
        private static readonly MethodInfo __standardDeviationPopulationInt64Async;
        private static readonly MethodInfo __standardDeviationPopulationInt64WithSelector;
        private static readonly MethodInfo __standardDeviationPopulationInt64WithSelectorAsync;
        private static readonly MethodInfo __standardDeviationPopulationNullableDecimal;
        private static readonly MethodInfo __standardDeviationPopulationNullableDecimalAsync;
        private static readonly MethodInfo __standardDeviationPopulationNullableDecimalWithSelector;
        private static readonly MethodInfo __standardDeviationPopulationNullableDecimalWithSelectorAsync;
        private static readonly MethodInfo __standardDeviationPopulationNullableDouble;
        private static readonly MethodInfo __standardDeviationPopulationNullableDoubleAsync;
        private static readonly MethodInfo __standardDeviationPopulationNullableDoubleWithSelector;
        private static readonly MethodInfo __standardDeviationPopulationNullableDoubleWithSelectorAsync;
        private static readonly MethodInfo __standardDeviationPopulationNullableInt32;
        private static readonly MethodInfo __standardDeviationPopulationNullableInt32Async;
        private static readonly MethodInfo __standardDeviationPopulationNullableInt32WithSelector;
        private static readonly MethodInfo __standardDeviationPopulationNullableInt32WithSelectorAsync;
        private static readonly MethodInfo __standardDeviationPopulationNullableInt64;
        private static readonly MethodInfo __standardDeviationPopulationNullableInt64Async;
        private static readonly MethodInfo __standardDeviationPopulationNullableInt64WithSelector;
        private static readonly MethodInfo __standardDeviationPopulationNullableInt64WithSelectorAsync;
        private static readonly MethodInfo __standardDeviationPopulationNullableSingle;
        private static readonly MethodInfo __standardDeviationPopulationNullableSingleAsync;
        private static readonly MethodInfo __standardDeviationPopulationNullableSingleWithSelector;
        private static readonly MethodInfo __standardDeviationPopulationNullableSingleWithSelectorAsync;
        private static readonly MethodInfo __standardDeviationPopulationSingle;
        private static readonly MethodInfo __standardDeviationPopulationSingleAsync;
        private static readonly MethodInfo __standardDeviationPopulationSingleWithSelector;
        private static readonly MethodInfo __standardDeviationPopulationSingleWithSelectorAsync;
        private static readonly MethodInfo __standardDeviationSampleDecimal;
        private static readonly MethodInfo __standardDeviationSampleDecimalAsync;
        private static readonly MethodInfo __standardDeviationSampleDecimalWithSelector;
        private static readonly MethodInfo __standardDeviationSampleDecimalWithSelectorAsync;
        private static readonly MethodInfo __standardDeviationSampleDouble;
        private static readonly MethodInfo __standardDeviationSampleDoubleAsync;
        private static readonly MethodInfo __standardDeviationSampleDoubleWithSelector;
        private static readonly MethodInfo __standardDeviationSampleDoubleWithSelectorAsync;
        private static readonly MethodInfo __standardDeviationSampleInt32;
        private static readonly MethodInfo __standardDeviationSampleInt32Async;
        private static readonly MethodInfo __standardDeviationSampleInt32WithSelector;
        private static readonly MethodInfo __standardDeviationSampleInt32WithSelectorAsync;
        private static readonly MethodInfo __standardDeviationSampleInt64;
        private static readonly MethodInfo __standardDeviationSampleInt64Async;
        private static readonly MethodInfo __standardDeviationSampleInt64WithSelector;
        private static readonly MethodInfo __standardDeviationSampleInt64WithSelectorAsync;
        private static readonly MethodInfo __standardDeviationSampleNullableDecimal;
        private static readonly MethodInfo __standardDeviationSampleNullableDecimalAsync;
        private static readonly MethodInfo __standardDeviationSampleNullableDecimalWithSelector;
        private static readonly MethodInfo __standardDeviationSampleNullableDecimalWithSelectorAsync;
        private static readonly MethodInfo __standardDeviationSampleNullableDouble;
        private static readonly MethodInfo __standardDeviationSampleNullableDoubleAsync;
        private static readonly MethodInfo __standardDeviationSampleNullableDoubleWithSelector;
        private static readonly MethodInfo __standardDeviationSampleNullableDoubleWithSelectorAsync;
        private static readonly MethodInfo __standardDeviationSampleNullableInt32;
        private static readonly MethodInfo __standardDeviationSampleNullableInt32Async;
        private static readonly MethodInfo __standardDeviationSampleNullableInt32WithSelector;
        private static readonly MethodInfo __standardDeviationSampleNullableInt32WithSelectorAsync;
        private static readonly MethodInfo __standardDeviationSampleNullableInt64;
        private static readonly MethodInfo __standardDeviationSampleNullableInt64Async;
        private static readonly MethodInfo __standardDeviationSampleNullableInt64WithSelector;
        private static readonly MethodInfo __standardDeviationSampleNullableInt64WithSelectorAsync;
        private static readonly MethodInfo __standardDeviationSampleNullableSingle;
        private static readonly MethodInfo __standardDeviationSampleNullableSingleAsync;
        private static readonly MethodInfo __standardDeviationSampleNullableSingleWithSelector;
        private static readonly MethodInfo __standardDeviationSampleNullableSingleWithSelectorAsync;
        private static readonly MethodInfo __standardDeviationSampleSingle;
        private static readonly MethodInfo __standardDeviationSampleSingleAsync;
        private static readonly MethodInfo __standardDeviationSampleSingleWithSelector;
        private static readonly MethodInfo __standardDeviationSampleSingleWithSelectorAsync;
        private static readonly MethodInfo __sumDecimalAsync;
        private static readonly MethodInfo __sumDecimalWithSelectorAsync;
        private static readonly MethodInfo __sumDoubleAsync;
        private static readonly MethodInfo __sumDoubleWithSelectorAsync;
        private static readonly MethodInfo __sumInt32Async;
        private static readonly MethodInfo __sumInt32WithSelectorAsync;
        private static readonly MethodInfo __sumInt64Async;
        private static readonly MethodInfo __sumInt64WithSelectorAsync;
        private static readonly MethodInfo __sumNullableDecimalAsync;
        private static readonly MethodInfo __sumNullableDecimalWithSelectorAsync;
        private static readonly MethodInfo __sumNullableDoubleAsync;
        private static readonly MethodInfo __sumNullableDoubleWithSelectorAsync;
        private static readonly MethodInfo __sumNullableInt32Async;
        private static readonly MethodInfo __sumNullableInt32WithSelectorAsync;
        private static readonly MethodInfo __sumNullableInt64Async;
        private static readonly MethodInfo __sumNullableInt64WithSelectorAsync;
        private static readonly MethodInfo __sumNullableSingleAsync;
        private static readonly MethodInfo __sumNullableSingleWithSelectorAsync;
        private static readonly MethodInfo __sumSingleAsync;
        private static readonly MethodInfo __sumSingleWithSelectorAsync;

        // static constructor
        static MongoQueryableMethod()
        {
            __anyAsync = new Func<IQueryable<object>, CancellationToken, Task<bool>>(MongoQueryable.AnyAsync).Method.GetGenericMethodDefinition();
            __anyWithPredicateAsync = new Func<IQueryable<object>, Expression<Func<object, bool>>, CancellationToken, Task<bool>>(MongoQueryable.AnyAsync).Method.GetGenericMethodDefinition();
            __averageDecimalAsync = new Func<IQueryable<decimal>, CancellationToken, Task<decimal>>(MongoQueryable.AverageAsync).Method;
            __averageDecimalWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, decimal>>, CancellationToken, Task<decimal>>(MongoQueryable.AverageAsync).Method.GetGenericMethodDefinition();
            __averageDoubleAsync = new Func<IQueryable<double>, CancellationToken, Task<double>>(MongoQueryable.AverageAsync).Method;
            __averageDoubleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, double>>, CancellationToken, Task<double>>(MongoQueryable.AverageAsync).Method.GetGenericMethodDefinition();
            __averageInt32Async = new Func<IQueryable<int>, CancellationToken, Task<double>>(MongoQueryable.AverageAsync).Method;
            __averageInt32WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, int>>, CancellationToken, Task<double>>(MongoQueryable.AverageAsync).Method.GetGenericMethodDefinition();
            __averageInt64Async = new Func<IQueryable<long>, CancellationToken, Task<double>>(MongoQueryable.AverageAsync).Method;
            __averageInt64WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, long>>, CancellationToken, Task<double>>(MongoQueryable.AverageAsync).Method.GetGenericMethodDefinition();
            __averageNullableDecimalAsync = new Func<IQueryable<decimal?>, CancellationToken, Task<decimal?>>(MongoQueryable.AverageAsync).Method;
            __averageNullableDecimalWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, decimal?>>, CancellationToken, Task<decimal?>>(MongoQueryable.AverageAsync).Method.GetGenericMethodDefinition();
            __averageNullableDoubleAsync = new Func<IQueryable<double?>, CancellationToken, Task<double?>>(MongoQueryable.AverageAsync).Method;
            __averageNullableDoubleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, double?>>, CancellationToken, Task<double?>>(MongoQueryable.AverageAsync).Method.GetGenericMethodDefinition();
            __averageNullableInt32Async = new Func<IQueryable<int?>, CancellationToken, Task<double?>>(MongoQueryable.AverageAsync).Method;
            __averageNullableInt32WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, int?>>, CancellationToken, Task<double?>>(MongoQueryable.AverageAsync).Method.GetGenericMethodDefinition();
            __averageNullableInt64Async = new Func<IQueryable<long?>, CancellationToken, Task<double?>>(MongoQueryable.AverageAsync).Method;
            __averageNullableInt64WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, long?>>, CancellationToken, Task<double?>>(MongoQueryable.AverageAsync).Method.GetGenericMethodDefinition();
            __averageNullableSingleAsync = new Func<IQueryable<float?>, CancellationToken, Task<float?>>(MongoQueryable.AverageAsync).Method;
            __averageNullableSingleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, float?>>, CancellationToken, Task<float?>>(MongoQueryable.AverageAsync).Method.GetGenericMethodDefinition();
            __averageSingleAsync = new Func<IQueryable<float>, CancellationToken, Task<float>>(MongoQueryable.AverageAsync).Method;
            __averageSingleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, float>>, CancellationToken, Task<float>>(MongoQueryable.AverageAsync).Method.GetGenericMethodDefinition();
            __countAsync = new Func<IQueryable<object>, CancellationToken, Task<int>>(MongoQueryable.CountAsync).Method.GetGenericMethodDefinition();
            __countWithPredicateAsync = new Func<IQueryable<object>, Expression<Func<object, bool>>, CancellationToken, Task<int>>(MongoQueryable.CountAsync).Method.GetGenericMethodDefinition();
            __firstAsync = new Func<IQueryable<object>, CancellationToken, object>(MongoQueryable.FirstAsync).Method.GetGenericMethodDefinition();
            __firstOrDefaultAsync = new Func<IQueryable<object>, CancellationToken, object>(MongoQueryable.FirstOrDefaultAsync).Method.GetGenericMethodDefinition();
            __firstOrDefaultWithPredicateAsync = new Func<IQueryable<object>, Expression<Func<object, bool>>, CancellationToken, object>(MongoQueryable.FirstOrDefaultAsync).Method.GetGenericMethodDefinition();
            __firstWithPredicateAsync = new Func<IQueryable<object>, Expression<Func<object, bool>>, CancellationToken, object>(MongoQueryable.FirstAsync).Method.GetGenericMethodDefinition();
            __longCountAsync = new Func<IQueryable<object>, CancellationToken, Task<long>>(MongoQueryable.LongCountAsync).Method.GetGenericMethodDefinition();
            __longCountWithPredicateAsync = new Func<IQueryable<object>, Expression<Func<object, bool>>, CancellationToken, Task<long>>(MongoQueryable.LongCountAsync).Method.GetGenericMethodDefinition();
            __maxAsync = new Func<IQueryable<object>, CancellationToken, Task<object>>(MongoQueryable.MaxAsync).Method.GetGenericMethodDefinition();
            __maxWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, object>>, CancellationToken, Task<object>>(MongoQueryable.MaxAsync).Method.GetGenericMethodDefinition();
            __minAsync = new Func<IQueryable<object>, CancellationToken, Task<object>>(MongoQueryable.MinAsync).Method.GetGenericMethodDefinition();
            __minWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, object>>, CancellationToken, Task<object>>(MongoQueryable.MinAsync).Method.GetGenericMethodDefinition();
            __sample = new Func<IQueryable<object>, long, IQueryable<object>>(MongoQueryable.Sample).Method.GetGenericMethodDefinition();
            __singleAsync = new Func<IQueryable<object>, CancellationToken, Task<object>>(MongoQueryable.SingleAsync).Method.GetGenericMethodDefinition();
            __singleOrDefaultAsync = new Func<IQueryable<object>, CancellationToken, Task<object>>(MongoQueryable.SingleOrDefaultAsync).Method.GetGenericMethodDefinition();
            __singleOrDefaultWithPredicateAsync = new Func<IQueryable<object>, Expression<Func<object, bool>>, CancellationToken, Task<object>>(MongoQueryable.SingleOrDefaultAsync).Method.GetGenericMethodDefinition();
            __singleWithPredicateAsync = new Func<IQueryable<object>, Expression<Func<object, bool>>, CancellationToken, Task<object>>(MongoQueryable.SingleAsync).Method.GetGenericMethodDefinition();
            __standardDeviationPopulationDecimal = new Func<IQueryable<decimal>, decimal>(MongoQueryable.StandardDeviationPopulation).Method;
            __standardDeviationPopulationDecimalAsync = new Func<IQueryable<decimal>, CancellationToken, Task<decimal>>(MongoQueryable.StandardDeviationPopulationAsync).Method;
            __standardDeviationPopulationDecimalWithSelector = new Func<IQueryable<object>, Expression<Func<object, decimal>>, decimal>(MongoQueryable.StandardDeviationPopulation).Method.GetGenericMethodDefinition();
            __standardDeviationPopulationDecimalWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, decimal>>, CancellationToken, Task<decimal>>(MongoQueryable.StandardDeviationPopulationAsync).Method.GetGenericMethodDefinition();
            __standardDeviationPopulationDouble = new Func<IQueryable<double>, double>(MongoQueryable.StandardDeviationPopulation).Method;
            __standardDeviationPopulationDoubleAsync = new Func<IQueryable<double>, CancellationToken, Task<double>>(MongoQueryable.StandardDeviationPopulationAsync).Method;
            __standardDeviationPopulationDoubleWithSelector = new Func<IQueryable<object>, Expression<Func<object, double>>, double>(MongoQueryable.StandardDeviationPopulation).Method.GetGenericMethodDefinition();
            __standardDeviationPopulationDoubleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, double>>, CancellationToken, Task<double>>(MongoQueryable.StandardDeviationPopulationAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationPopulationInt32 = new Func<IQueryable<int>, double>(MongoQueryable.StandardDeviationPopulation).Method;
            __standardDeviationPopulationInt32Async = new Func<IQueryable<int>, CancellationToken, Task<double>>(MongoQueryable.StandardDeviationPopulationAsync).Method;
            __standardDeviationPopulationInt32WithSelector = new Func<IQueryable<object>, Expression<Func<object, int>>, double>(MongoQueryable.StandardDeviationPopulation).Method.GetGenericMethodDefinition();
            __standardDeviationPopulationInt32WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, int>>, CancellationToken, Task<double>>(MongoQueryable.StandardDeviationPopulationAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationPopulationInt64 = new Func<IQueryable<long>, double>(MongoQueryable.StandardDeviationPopulation).Method;
            __standardDeviationPopulationInt64Async = new Func<IQueryable<long>, CancellationToken, Task<double>>(MongoQueryable.StandardDeviationPopulationAsync).Method;
            __standardDeviationPopulationInt64WithSelector = new Func<IQueryable<object>, Expression<Func<object, long>>, double>(MongoQueryable.StandardDeviationPopulation).Method.GetGenericMethodDefinition();
            __standardDeviationPopulationInt64WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, long>>, CancellationToken, Task<double>>(MongoQueryable.StandardDeviationPopulationAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationPopulationNullableDecimal = new Func<IQueryable<decimal?>, decimal?>(MongoQueryable.StandardDeviationPopulation).Method;
            __standardDeviationPopulationNullableDecimalAsync = new Func<IQueryable<decimal?>, CancellationToken, Task<decimal?>>(MongoQueryable.StandardDeviationPopulationAsync).Method;
            __standardDeviationPopulationNullableDecimalWithSelector = new Func<IQueryable<object>, Expression<Func<object, decimal?>>, decimal?>(MongoQueryable.StandardDeviationPopulation).Method.GetGenericMethodDefinition();
            __standardDeviationPopulationNullableDecimalWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, decimal?>>, CancellationToken, Task<decimal?>>(MongoQueryable.StandardDeviationPopulationAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationPopulationNullableDouble = new Func<IQueryable<double?>, double?>(MongoQueryable.StandardDeviationPopulation).Method;
            __standardDeviationPopulationNullableDoubleAsync = new Func<IQueryable<double?>, CancellationToken, Task<double?>>(MongoQueryable.StandardDeviationPopulationAsync).Method;
            __standardDeviationPopulationNullableDoubleWithSelector = new Func<IQueryable<object>, Expression<Func<object, double?>>, double?>(MongoQueryable.StandardDeviationPopulation).Method.GetGenericMethodDefinition();
            __standardDeviationPopulationNullableDoubleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, double?>>, CancellationToken, Task<double?>>(MongoQueryable.StandardDeviationPopulationAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationPopulationNullableInt32 = new Func<IQueryable<int?>, double?>(MongoQueryable.StandardDeviationPopulation).Method;
            __standardDeviationPopulationNullableInt32Async = new Func<IQueryable<int?>, CancellationToken, Task<double?>>(MongoQueryable.StandardDeviationPopulationAsync).Method;
            __standardDeviationPopulationNullableInt32WithSelector = new Func<IQueryable<object>, Expression<Func<object, int?>>, double?>(MongoQueryable.StandardDeviationPopulation).Method.GetGenericMethodDefinition();
            __standardDeviationPopulationNullableInt32WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, int?>>, CancellationToken, Task<double?>>(MongoQueryable.StandardDeviationPopulationAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationPopulationNullableInt64 = new Func<IQueryable<long?>, double?>(MongoQueryable.StandardDeviationPopulation).Method;
            __standardDeviationPopulationNullableInt64Async = new Func<IQueryable<long?>, CancellationToken, Task<double?>>(MongoQueryable.StandardDeviationPopulationAsync).Method;
            __standardDeviationPopulationNullableInt64WithSelector = new Func<IQueryable<object>, Expression<Func<object, long?>>, double?>(MongoQueryable.StandardDeviationPopulation).Method.GetGenericMethodDefinition();
            __standardDeviationPopulationNullableInt64WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, long?>>, CancellationToken, Task<double?>>(MongoQueryable.StandardDeviationPopulationAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationPopulationNullableSingle = new Func<IQueryable<float?>, float?>(MongoQueryable.StandardDeviationPopulation).Method;
            __standardDeviationPopulationNullableSingleAsync = new Func<IQueryable<float?>, CancellationToken, Task<float?>>(MongoQueryable.StandardDeviationPopulationAsync).Method;
            __standardDeviationPopulationNullableSingleWithSelector = new Func<IQueryable<object>, Expression<Func<object, float?>>, float?>(MongoQueryable.StandardDeviationPopulation).Method.GetGenericMethodDefinition();
            __standardDeviationPopulationNullableSingleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, float?>>, CancellationToken, Task<float?>>(MongoQueryable.StandardDeviationPopulationAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationPopulationSingle = new Func<IQueryable<float>, float>(MongoQueryable.StandardDeviationPopulation).Method;
            __standardDeviationPopulationSingleAsync = new Func<IQueryable<float>, CancellationToken, Task<float>>(MongoQueryable.StandardDeviationPopulationAsync).Method;
            __standardDeviationPopulationSingleWithSelector = new Func<IQueryable<object>, Expression<Func<object, float>>, float>(MongoQueryable.StandardDeviationPopulation).Method.GetGenericMethodDefinition();
            __standardDeviationPopulationSingleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, float>>, CancellationToken, Task<float>>(MongoQueryable.StandardDeviationPopulationAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationSampleDecimal = new Func<IQueryable<decimal>, decimal>(MongoQueryable.StandardDeviationSample).Method;
            __standardDeviationSampleDecimalAsync = new Func<IQueryable<decimal>, CancellationToken, Task<decimal>>(MongoQueryable.StandardDeviationSampleAsync).Method;
            __standardDeviationSampleDecimalWithSelector = new Func<IQueryable<object>, Expression<Func<object, decimal>>, decimal>(MongoQueryable.StandardDeviationSample).Method.GetGenericMethodDefinition();
            __standardDeviationSampleDecimalWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, decimal>>, CancellationToken, Task<decimal>>(MongoQueryable.StandardDeviationSampleAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationSampleDouble = new Func<IQueryable<double>, double>(MongoQueryable.StandardDeviationSample).Method;
            __standardDeviationSampleDoubleAsync = new Func<IQueryable<double>, CancellationToken, Task<double>>(MongoQueryable.StandardDeviationSampleAsync).Method;
            __standardDeviationSampleDoubleWithSelector = new Func<IQueryable<object>, Expression<Func<object, double>>, double>(MongoQueryable.StandardDeviationSample).Method.GetGenericMethodDefinition();
            __standardDeviationSampleDoubleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, double>>, CancellationToken, Task<double>>(MongoQueryable.StandardDeviationSampleAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationSampleInt32 = new Func<IQueryable<int>, double>(MongoQueryable.StandardDeviationSample).Method;
            __standardDeviationSampleInt32Async = new Func<IQueryable<int>, CancellationToken, Task<double>>(MongoQueryable.StandardDeviationSampleAsync).Method;
            __standardDeviationSampleInt32WithSelector = new Func<IQueryable<object>, Expression<Func<object, int>>, double>(MongoQueryable.StandardDeviationSample).Method.GetGenericMethodDefinition();
            __standardDeviationSampleInt32WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, int>>, CancellationToken, Task<double>>(MongoQueryable.StandardDeviationSampleAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationSampleInt64 = new Func<IQueryable<long>, double>(MongoQueryable.StandardDeviationSample).Method;
            __standardDeviationSampleInt64Async = new Func<IQueryable<long>, CancellationToken, Task<double>>(MongoQueryable.StandardDeviationSampleAsync).Method;
            __standardDeviationSampleInt64WithSelector = new Func<IQueryable<object>, Expression<Func<object, long>>, double>(MongoQueryable.StandardDeviationSample).Method.GetGenericMethodDefinition();
            __standardDeviationSampleInt64WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, long>>, CancellationToken, Task<double>>(MongoQueryable.StandardDeviationSampleAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationSampleNullableDecimal = new Func<IQueryable<decimal?>, decimal?>(MongoQueryable.StandardDeviationSample).Method;
            __standardDeviationSampleNullableDecimalAsync = new Func<IQueryable<decimal?>, CancellationToken, Task<decimal?>>(MongoQueryable.StandardDeviationSampleAsync).Method;
            __standardDeviationSampleNullableDecimalWithSelector = new Func<IQueryable<object>, Expression<Func<object, decimal?>>, decimal?>(MongoQueryable.StandardDeviationSample).Method.GetGenericMethodDefinition();
            __standardDeviationSampleNullableDecimalWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, decimal?>>, CancellationToken, Task<decimal?>>(MongoQueryable.StandardDeviationSampleAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationSampleNullableDouble = new Func<IQueryable<double?>, double?>(MongoQueryable.StandardDeviationSample).Method;
            __standardDeviationSampleNullableDoubleAsync = new Func<IQueryable<double?>, CancellationToken, Task<double?>>(MongoQueryable.StandardDeviationSampleAsync).Method;
            __standardDeviationSampleNullableDoubleWithSelector = new Func<IQueryable<object>, Expression<Func<object, double?>>, double?>(MongoQueryable.StandardDeviationSample).Method.GetGenericMethodDefinition();
            __standardDeviationSampleNullableDoubleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, double?>>, CancellationToken, Task<double?>>(MongoQueryable.StandardDeviationSampleAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationSampleNullableInt32 = new Func<IQueryable<int?>, double?>(MongoQueryable.StandardDeviationSample).Method;
            __standardDeviationSampleNullableInt32Async = new Func<IQueryable<int?>, CancellationToken, Task<double?>>(MongoQueryable.StandardDeviationSampleAsync).Method;
            __standardDeviationSampleNullableInt32WithSelector = new Func<IQueryable<object>, Expression<Func<object, int?>>, double?>(MongoQueryable.StandardDeviationSample).Method.GetGenericMethodDefinition();
            __standardDeviationSampleNullableInt32WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, int?>>, CancellationToken, Task<double?>>(MongoQueryable.StandardDeviationSampleAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationSampleNullableInt64 = new Func<IQueryable<long?>, double?>(MongoQueryable.StandardDeviationSample).Method;
            __standardDeviationSampleNullableInt64Async = new Func<IQueryable<long?>, CancellationToken, Task<double?>>(MongoQueryable.StandardDeviationSampleAsync).Method;
            __standardDeviationSampleNullableInt64WithSelector = new Func<IQueryable<object>, Expression<Func<object, long?>>, double?>(MongoQueryable.StandardDeviationSample).Method.GetGenericMethodDefinition();
            __standardDeviationSampleNullableInt64WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, long?>>, CancellationToken, Task<double?>>(MongoQueryable.StandardDeviationSampleAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationSampleNullableSingle = new Func<IQueryable<float?>, float?>(MongoQueryable.StandardDeviationSample).Method;
            __standardDeviationSampleNullableSingleAsync = new Func<IQueryable<float?>, CancellationToken, Task<float?>>(MongoQueryable.StandardDeviationSampleAsync).Method;
            __standardDeviationSampleNullableSingleWithSelector = new Func<IQueryable<object>, Expression<Func<object, float?>>, float?>(MongoQueryable.StandardDeviationSample).Method.GetGenericMethodDefinition();
            __standardDeviationSampleNullableSingleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, float?>>, CancellationToken, Task<float?>>(MongoQueryable.StandardDeviationSampleAsync).Method.GetGenericMethodDefinition(); ;
            __standardDeviationSampleSingle = new Func<IQueryable<float>, float>(MongoQueryable.StandardDeviationSample).Method;
            __standardDeviationSampleSingleAsync = new Func<IQueryable<float>, CancellationToken, Task<float>>(MongoQueryable.StandardDeviationSampleAsync).Method;
            __standardDeviationSampleSingleWithSelector = new Func<IQueryable<object>, Expression<Func<object, float>>, float>(MongoQueryable.StandardDeviationSample).Method.GetGenericMethodDefinition();
            __standardDeviationSampleSingleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, float>>, CancellationToken, Task<float>>(MongoQueryable.StandardDeviationSampleAsync).Method.GetGenericMethodDefinition(); ;
            __sumDecimalAsync = new Func<IQueryable<decimal>, CancellationToken, Task<decimal>>(MongoQueryable.SumAsync).Method;
            __sumDecimalWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, decimal>>, CancellationToken, Task<decimal>>(MongoQueryable.SumAsync).Method.GetGenericMethodDefinition();
            __sumDoubleAsync = new Func<IQueryable<double>, CancellationToken, Task<double>>(MongoQueryable.SumAsync).Method;
            __sumDoubleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, double>>, CancellationToken, Task<double>>(MongoQueryable.SumAsync).Method.GetGenericMethodDefinition();
            __sumInt32Async = new Func<IQueryable<int>, CancellationToken, Task<int>>(MongoQueryable.SumAsync).Method;
            __sumInt32WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, int>>, CancellationToken, Task<int>>(MongoQueryable.SumAsync).Method.GetGenericMethodDefinition();
            __sumInt64Async = new Func<IQueryable<long>, CancellationToken, Task<long>>(MongoQueryable.SumAsync).Method;
            __sumInt64WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, long>>, CancellationToken, Task<long>>(MongoQueryable.SumAsync).Method.GetGenericMethodDefinition();
            __sumNullableDecimalAsync = new Func<IQueryable<decimal?>, CancellationToken, Task<decimal?>>(MongoQueryable.SumAsync).Method;
            __sumNullableDecimalWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, decimal?>>, CancellationToken, Task<decimal?>>(MongoQueryable.SumAsync).Method.GetGenericMethodDefinition();
            __sumNullableDoubleAsync = new Func<IQueryable<double?>, CancellationToken, Task<double?>>(MongoQueryable.SumAsync).Method;
            __sumNullableDoubleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, double?>>, CancellationToken, Task<double?>>(MongoQueryable.SumAsync).Method.GetGenericMethodDefinition();
            __sumNullableInt32Async = new Func<IQueryable<int?>, CancellationToken, Task<int?>>(MongoQueryable.SumAsync).Method;
            __sumNullableInt32WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, int?>>, CancellationToken, Task<int?>>(MongoQueryable.SumAsync).Method.GetGenericMethodDefinition();
            __sumNullableInt64Async = new Func<IQueryable<long?>, CancellationToken, Task<long?>>(MongoQueryable.SumAsync).Method;
            __sumNullableInt64WithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, long?>>, CancellationToken, Task<long?>>(MongoQueryable.SumAsync).Method.GetGenericMethodDefinition();
            __sumNullableSingleAsync = new Func<IQueryable<float?>, CancellationToken, Task<float?>>(MongoQueryable.SumAsync).Method;
            __sumNullableSingleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, float?>>, CancellationToken, Task<float?>>(MongoQueryable.SumAsync).Method.GetGenericMethodDefinition();
            __sumSingleAsync = new Func<IQueryable<float>, CancellationToken, Task<float>>(MongoQueryable.SumAsync).Method;
            __sumSingleWithSelectorAsync = new Func<IQueryable<object>, Expression<Func<object, float>>, CancellationToken, Task<float>>(MongoQueryable.SumAsync).Method.GetGenericMethodDefinition();
        }

        // public properties
        public static MethodInfo AnyAsync => __anyAsync;
        public static MethodInfo AnyWithPredicateAsync => __anyWithPredicateAsync;
        public static MethodInfo AverageDecimalAsync => __averageDecimalAsync;
        public static MethodInfo AverageDecimalWithSelectorAsync => __averageDecimalWithSelectorAsync;
        public static MethodInfo AverageDoubleAsync => __averageDoubleAsync;
        public static MethodInfo AverageDoubleWithSelectorAsync => __averageDoubleWithSelectorAsync;
        public static MethodInfo AverageInt32Async => __averageInt32Async;
        public static MethodInfo AverageInt32WithSelectorAsync => __averageInt32WithSelectorAsync;
        public static MethodInfo AverageInt64Async => __averageInt64Async;
        public static MethodInfo AverageInt64WithSelectorAsync => __averageInt64WithSelectorAsync;
        public static MethodInfo AverageNullableDecimalAsync => __averageNullableDecimalAsync;
        public static MethodInfo AverageNullableDecimalWithSelectorAsync => __averageNullableDecimalWithSelectorAsync;
        public static MethodInfo AverageNullableDoubleAsync => __averageNullableDoubleAsync;
        public static MethodInfo AverageNullableDoubleWithSelectorAsync => __averageNullableDoubleWithSelectorAsync;
        public static MethodInfo AverageNullableInt32Async => __averageNullableInt32Async;
        public static MethodInfo AverageNullableInt32WithSelectorAsync => __averageNullableInt32WithSelectorAsync;
        public static MethodInfo AverageNullableInt64Async => __averageNullableInt64Async;
        public static MethodInfo AverageNullableInt64WithSelectorAsync => __averageNullableInt64WithSelectorAsync;
        public static MethodInfo AverageNullableSingleAsync => __averageNullableSingleAsync;
        public static MethodInfo AverageNullableSingleWithSelectorAsync => __averageNullableSingleWithSelectorAsync;
        public static MethodInfo AverageSingleAsync => __averageSingleAsync;
        public static MethodInfo AverageSingleWithSelectorAsync => __averageSingleWithSelectorAsync;
        public static MethodInfo CountAsync => __countAsync;
        public static MethodInfo CountWithPredicateAsync => __countWithPredicateAsync;
        public static MethodInfo FirstAsync => __firstAsync;
        public static MethodInfo FirstOrDefaultAsync => __firstOrDefaultAsync;
        public static MethodInfo FirstOrDefaultWithPredicateAsync => __firstOrDefaultWithPredicateAsync;
        public static MethodInfo FirstWithPredicateAsync => __firstWithPredicateAsync;
        public static MethodInfo LongCountAsync => __longCountAsync;
        public static MethodInfo LongCountWithPredicateAsync => __longCountWithPredicateAsync;
        public static MethodInfo MaxAsync => __maxAsync;
        public static MethodInfo MaxWithSelectorAsync => __maxWithSelectorAsync;
        public static MethodInfo MinAsync => __minAsync;
        public static MethodInfo MinWithSelectorAsync => __minWithSelectorAsync;
        public static MethodInfo Sample => __sample;
        public static MethodInfo SingleAsync => __singleAsync;
        public static MethodInfo SingleOrDefaultAsync => __singleOrDefaultAsync;
        public static MethodInfo SingleOrDefaultWithPredicateAsync => __singleOrDefaultWithPredicateAsync;
        public static MethodInfo SingleWithPredicateAsync => __singleWithPredicateAsync;
        public static MethodInfo StandardDeviationPopulationDecimal => __standardDeviationPopulationDecimal;
        public static MethodInfo StandardDeviationPopulationDecimalAsync => __standardDeviationPopulationDecimalAsync;
        public static MethodInfo StandardDeviationPopulationDecimalWithSelector => __standardDeviationPopulationDecimalWithSelector;
        public static MethodInfo StandardDeviationPopulationDecimalWithSelectorAsync => __standardDeviationPopulationDecimalWithSelectorAsync;
        public static MethodInfo StandardDeviationPopulationDouble => __standardDeviationPopulationDouble;
        public static MethodInfo StandardDeviationPopulationDoubleAsync => __standardDeviationPopulationDoubleAsync;
        public static MethodInfo StandardDeviationPopulationDoubleWithSelector => __standardDeviationPopulationDoubleWithSelector;
        public static MethodInfo StandardDeviationPopulationDoubleWithSelectorAsync => __standardDeviationPopulationDoubleWithSelectorAsync;
        public static MethodInfo StandardDeviationPopulationInt32 => __standardDeviationPopulationInt32;
        public static MethodInfo StandardDeviationPopulationInt32Async => __standardDeviationPopulationInt32Async;
        public static MethodInfo StandardDeviationPopulationInt32WithSelector => __standardDeviationPopulationInt32WithSelector;
        public static MethodInfo StandardDeviationPopulationInt32WithSelectorAsync => __standardDeviationPopulationInt32WithSelectorAsync;
        public static MethodInfo StandardDeviationPopulationInt64 => __standardDeviationPopulationInt64;
        public static MethodInfo StandardDeviationPopulationInt64Async => __standardDeviationPopulationInt64Async;
        public static MethodInfo StandardDeviationPopulationInt64WithSelector => __standardDeviationPopulationInt64WithSelector;
        public static MethodInfo StandardDeviationPopulationInt64WithSelectorAsync => __standardDeviationPopulationInt64WithSelectorAsync;
        public static MethodInfo StandardDeviationPopulationNullableDecimal => __standardDeviationPopulationNullableDecimal;
        public static MethodInfo StandardDeviationPopulationNullableDecimalAsync => __standardDeviationPopulationNullableDecimalAsync;
        public static MethodInfo StandardDeviationPopulationNullableDecimalWithSelector => __standardDeviationPopulationNullableDecimalWithSelector;
        public static MethodInfo StandardDeviationPopulationNullableDecimalWithSelectorAsync => __standardDeviationPopulationNullableDecimalWithSelectorAsync;
        public static MethodInfo StandardDeviationPopulationNullableDouble => __standardDeviationPopulationNullableDouble;
        public static MethodInfo StandardDeviationPopulationNullableDoubleAsync => __standardDeviationPopulationNullableDoubleAsync;
        public static MethodInfo StandardDeviationPopulationNullableDoubleWithSelector => __standardDeviationPopulationNullableDoubleWithSelector;
        public static MethodInfo StandardDeviationPopulationNullableDoubleWithSelectorAsync => __standardDeviationPopulationNullableDoubleWithSelectorAsync;
        public static MethodInfo StandardDeviationPopulationNullableInt32 => __standardDeviationPopulationNullableInt32;
        public static MethodInfo StandardDeviationPopulationNullableInt32Async => __standardDeviationPopulationNullableInt32Async;
        public static MethodInfo StandardDeviationPopulationNullableInt32WithSelector => __standardDeviationPopulationNullableInt32WithSelector;
        public static MethodInfo StandardDeviationPopulationNullableInt32WithSelectorAsync => __standardDeviationPopulationNullableInt32WithSelectorAsync;
        public static MethodInfo StandardDeviationPopulationNullableInt64 => __standardDeviationPopulationNullableInt64;
        public static MethodInfo StandardDeviationPopulationNullableInt64Async => __standardDeviationPopulationNullableInt64Async;
        public static MethodInfo StandardDeviationPopulationNullableInt64WithSelector => __standardDeviationPopulationNullableInt64WithSelector;
        public static MethodInfo StandardDeviationPopulationNullableInt64WithSelectorAsync => __standardDeviationPopulationNullableInt64WithSelectorAsync;
        public static MethodInfo StandardDeviationPopulationNullableSingle => __standardDeviationPopulationNullableSingle;
        public static MethodInfo StandardDeviationPopulationNullableSingleAsync => __standardDeviationPopulationNullableSingleAsync;
        public static MethodInfo StandardDeviationPopulationNullableSingleWithSelector => __standardDeviationPopulationNullableSingleWithSelector;
        public static MethodInfo StandardDeviationPopulationNullableSingleWithSelectorAsync => __standardDeviationPopulationNullableSingleWithSelectorAsync;
        public static MethodInfo StandardDeviationPopulationSingle => __standardDeviationPopulationSingle;
        public static MethodInfo StandardDeviationPopulationSingleAsync => __standardDeviationPopulationSingleAsync;
        public static MethodInfo StandardDeviationPopulationSingleWithSelector => __standardDeviationPopulationSingleWithSelector;
        public static MethodInfo StandardDeviationPopulationSingleWithSelectorAsync => __standardDeviationPopulationSingleWithSelectorAsync;
        public static MethodInfo StandardDeviationSampleDecimal => __standardDeviationSampleDecimal;
        public static MethodInfo StandardDeviationSampleDecimalAsync => __standardDeviationSampleDecimalAsync;
        public static MethodInfo StandardDeviationSampleDecimalWithSelector => __standardDeviationSampleDecimalWithSelector;
        public static MethodInfo StandardDeviationSampleDecimalWithSelectorAsync => __standardDeviationSampleDecimalWithSelectorAsync;
        public static MethodInfo StandardDeviationSampleDouble => __standardDeviationSampleDouble;
        public static MethodInfo StandardDeviationSampleDoubleAsync => __standardDeviationSampleDoubleAsync;
        public static MethodInfo StandardDeviationSampleDoubleWithSelector => __standardDeviationSampleDoubleWithSelector;
        public static MethodInfo StandardDeviationSampleDoubleWithSelectorAsync => __standardDeviationSampleDoubleWithSelectorAsync;
        public static MethodInfo StandardDeviationSampleInt32 => __standardDeviationSampleInt32;
        public static MethodInfo StandardDeviationSampleInt32Async => __standardDeviationSampleInt32Async;
        public static MethodInfo StandardDeviationSampleInt32WithSelector => __standardDeviationSampleInt32WithSelector;
        public static MethodInfo StandardDeviationSampleInt32WithSelectorAsync => __standardDeviationSampleInt32WithSelectorAsync;
        public static MethodInfo StandardDeviationSampleInt64 => __standardDeviationSampleInt64;
        public static MethodInfo StandardDeviationSampleInt64Async => __standardDeviationSampleInt64Async;
        public static MethodInfo StandardDeviationSampleInt64WithSelector => __standardDeviationSampleInt64WithSelector;
        public static MethodInfo StandardDeviationSampleInt64WithSelectorAsync => __standardDeviationSampleInt64WithSelectorAsync;
        public static MethodInfo StandardDeviationSampleNullableDecimal => __standardDeviationSampleNullableDecimal;
        public static MethodInfo StandardDeviationSampleNullableDecimalAsync => __standardDeviationSampleNullableDecimalAsync;
        public static MethodInfo StandardDeviationSampleNullableDecimalWithSelector => __standardDeviationSampleNullableDecimalWithSelector;
        public static MethodInfo StandardDeviationSampleNullableDecimalWithSelectorAsync => __standardDeviationSampleNullableDecimalWithSelectorAsync;
        public static MethodInfo StandardDeviationSampleNullableDouble => __standardDeviationSampleNullableDouble;
        public static MethodInfo StandardDeviationSampleNullableDoubleAsync => __standardDeviationSampleNullableDoubleAsync;
        public static MethodInfo StandardDeviationSampleNullableDoubleWithSelector => __standardDeviationSampleNullableDoubleWithSelector;
        public static MethodInfo StandardDeviationSampleNullableDoubleWithSelectorAsync => __standardDeviationSampleNullableDoubleWithSelectorAsync;
        public static MethodInfo StandardDeviationSampleNullableInt32 => __standardDeviationSampleNullableInt32;
        public static MethodInfo StandardDeviationSampleNullableInt32Async => __standardDeviationSampleNullableInt32Async;
        public static MethodInfo StandardDeviationSampleNullableInt32WithSelector => __standardDeviationSampleNullableInt32WithSelector;
        public static MethodInfo StandardDeviationSampleNullableInt32WithSelectorAsync => __standardDeviationSampleNullableInt32WithSelectorAsync;
        public static MethodInfo StandardDeviationSampleNullableInt64 => __standardDeviationSampleNullableInt64;
        public static MethodInfo StandardDeviationSampleNullableInt64Async => __standardDeviationSampleNullableInt64Async;
        public static MethodInfo StandardDeviationSampleNullableInt64WithSelector => __standardDeviationSampleNullableInt64WithSelector;
        public static MethodInfo StandardDeviationSampleNullableInt64WithSelectorAsync => __standardDeviationSampleNullableInt64WithSelectorAsync;
        public static MethodInfo StandardDeviationSampleNullableSingle => __standardDeviationSampleNullableSingle;
        public static MethodInfo StandardDeviationSampleNullableSingleAsync => __standardDeviationSampleNullableSingleAsync;
        public static MethodInfo StandardDeviationSampleNullableSingleWithSelector => __standardDeviationSampleNullableSingleWithSelector;
        public static MethodInfo StandardDeviationSampleNullableSingleWithSelectorAsync => __standardDeviationSampleNullableSingleWithSelectorAsync;
        public static MethodInfo StandardDeviationSampleSingle => __standardDeviationSampleSingle;
        public static MethodInfo StandardDeviationSampleSingleAsync => __standardDeviationSampleSingleAsync;
        public static MethodInfo StandardDeviationSampleSingleWithSelector => __standardDeviationSampleSingleWithSelector;
        public static MethodInfo StandardDeviationSampleSingleWithSelectorAsync => __standardDeviationSampleSingleWithSelectorAsync;
        public static MethodInfo SumDecimalAsync => __sumDecimalAsync;
        public static MethodInfo SumDecimalWithSelectorAsync => __sumDecimalWithSelectorAsync;
        public static MethodInfo SumDoubleAsync => __sumDoubleAsync;
        public static MethodInfo SumDoubleWithSelectorAsync => __sumDoubleWithSelectorAsync;
        public static MethodInfo SumInt32Async => __sumInt32Async;
        public static MethodInfo SumInt32WithSelectorAsync => __sumInt32WithSelectorAsync;
        public static MethodInfo SumInt64Async => __sumInt64Async;
        public static MethodInfo SumInt64WithSelectorAsync => __sumInt64WithSelectorAsync;
        public static MethodInfo SumNullableDecimalAsync => __sumNullableDecimalAsync;
        public static MethodInfo SumNullableDecimalWithSelectorAsync => __sumNullableDecimalWithSelectorAsync;
        public static MethodInfo SumNullableDoubleAsync => __sumNullableDoubleAsync;
        public static MethodInfo SumNullableDoubleWithSelectorAsync => __sumNullableDoubleWithSelectorAsync;
        public static MethodInfo SumNullableInt32Async => __sumNullableInt32Async;
        public static MethodInfo SumNullableInt32WithSelectorAsync => __sumNullableInt32WithSelectorAsync;
        public static MethodInfo SumNullableInt64Async => __sumNullableInt64Async;
        public static MethodInfo SumNullableInt64WithSelectorAsync => __sumNullableInt64WithSelectorAsync;
        public static MethodInfo SumNullableSingleAsync => __sumNullableSingleAsync;
        public static MethodInfo SumNullableSingleWithSelectorAsync => __sumNullableSingleWithSelectorAsync;
        public static MethodInfo SumSingleAsync => __sumSingleAsync;
        public static MethodInfo SumSingleWithSelectorAsync => __sumSingleWithSelectorAsync;
    }
}
