/* Copyright 2010-present MongoDB Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

namespace MongoDB.Driver.Linq3.Ast
{
    public enum AstNodeType
    {
        AddFieldsStage,
        AllFilter,
        AndExpression,
        AndFilter,
        BinaryExpression,
        BitsAllClearFilter,
        BitsAllSetFilter,
        BitsAnyClearFilter,
        BitsAnySetFilter,
        BoxFilter,
        BucketAutoStage,
        BucketStage,
        CenterFilter,
        CenterSphereFilter,
        CollStatsStage,
        ComparisonFilter,
        ComputedArrayExpression,
        ComputedDocumentExpression,
        CondExpression,
        ConstantExpression,
        ConvertExpression,
        CountStage,
        CurrentOpStage,
        CustomAccumulatorExpression,
        DateFromIsoWeekPartsExpression,
        DateFromPartsExpression,
        DateFromStringExpression,
        DatePartExpression,
        DateToPartsExpression,
        DateToStringExpression,
        ElemMatchFilter,
        ExistsFilter,
        ExprFilter,
        FacetStage,
        FieldExpression,
        FilterExpression,
        FilterField,
        FunctionExpression,
        GeoIntersectsFilter,
        GeoNearStage,
        GeoWithinFilter,
        GraphLookupStage,
        GroupStage,
        GtFilter,
        IncludeFieldProjectSpecification,
        IndexOfArrayExpression,
        IndexOfBytesExpression,
        IndexOfCPExpression,
        IndexStatsStage,
        InFilter,
        JsonSchemaFilter,
        LetExpression,
        LimitStage,
        ListLocalSessionsStage,
        ListSessionsStage,
        LookupStage,
        LTrimExpression,
        MapExpression,
        MatchStage,
        MergeStage,
        ModFilter,
        NaryExpression,
        NearFilter,
        NearSphereFilter,
        NinFilter,
        NotFilter,
        OrExpression,
        OrFilter,
        OutStage,
        Pipeline,
        PlanCacheStatsStage,
        ProjectStage,
        RangeExpression,
        RedactStage,
        ReduceExpression,
        RegexFilter,
        RegexExpression,
        ReplaceAllExpression,
        ReplaceOneExpression,
        ReplaceRootStage,
        RTrimExpression,
        SetFieldProjectSpecification,
        SetStage,
        SizeFilter,
        SliceExpression,
        SortStage,
        SwitchExpression,
        TernaryExpression,
        TextFilter,
        TrimExpression,
        TypeFilter,
        UnaryExpression,
        UnionWithStage,
        UnsetStage,
        UnwindStage,
        WhereFilter,
        ZipExpression
    }
}
